version: 2.1
jobs:
  build:
    docker:
      - image: patosai/ruby-gcc-embedded:0.0.1
    steps:
      - checkout
      - run:
          command: git submodule init && git submodule update --recursive
      - run:
          command: make test
      - run:
          command: make
